# -*- coding: utf-8 -*-
from __future__ import annotations

from ..environments import SessionMountRepository
from ..state import SQLiteStateStore
from ..state.repositories import (
    SqliteAgentCheckpointRepository,
    SqliteAgentLeaseRepository,
    SqliteAgentMailboxRepository,
    SqliteAgentProfileOverrideRepository,
    SqliteAgentReportRepository,
    SqliteAgentRuntimeRepository,
    SqliteAgentThreadBindingRepository,
    SqliteAssignmentRepository,
    SqliteBacklogItemRepository,
    SqliteCapabilityOverrideRepository,
    SqliteDecisionRequestRepository,
    SqliteExecutionRoutineRepository,
    SqliteFixedSopBindingRepository,
    SqliteFixedSopTemplateRepository,
    SqliteGoalOverrideRepository,
    SqliteGoalRepository,
    SqliteGovernanceControlRepository,
    SqliteIndustryInstanceRepository,
    SqliteKnowledgeChunkRepository,
    SqliteMediaAnalysisRepository,
    SqliteMemoryEntityViewRepository,
    SqliteMemoryFactIndexRepository,
    SqliteMemoryOpinionViewRepository,
    SqliteMemoryReflectionRunRepository,
    SqliteOperatingCycleRepository,
    SqliteOperatingLaneRepository,
    SqlitePredictionCaseRepository,
    SqlitePredictionRecommendationRepository,
    SqlitePredictionReviewRepository,
    SqlitePredictionScenarioRepository,
    SqlitePredictionSignalRepository,
    SqliteRoutineRunRepository,
    SqliteRuntimeFrameRepository,
    SqliteScheduleRepository,
    SqliteStrategyMemoryRepository,
    SqliteTaskRepository,
    SqliteTaskRuntimeRepository,
    SqliteWorkContextRepository,
    SqliteWorkflowPresetRepository,
    SqliteWorkflowRunRepository,
    SqliteWorkflowTemplateRepository,
)
from .runtime_bootstrap_models import RuntimeRepositories


def build_runtime_repositories(state_store: SQLiteStateStore) -> RuntimeRepositories:
    return RuntimeRepositories(
        task_repository=SqliteTaskRepository(state_store),
        task_runtime_repository=SqliteTaskRuntimeRepository(state_store),
        runtime_frame_repository=SqliteRuntimeFrameRepository(state_store),
        bootstrap_schedule_repository=SqliteScheduleRepository(state_store),
        schedule_repository=SqliteScheduleRepository(state_store),
        goal_repository=SqliteGoalRepository(state_store),
        work_context_repository=SqliteWorkContextRepository(state_store),
        decision_request_repository=SqliteDecisionRequestRepository(state_store),
        governance_control_repository=SqliteGovernanceControlRepository(state_store),
        capability_override_repository=SqliteCapabilityOverrideRepository(state_store),
        agent_profile_override_repository=SqliteAgentProfileOverrideRepository(
            state_store,
        ),
        agent_runtime_repository=SqliteAgentRuntimeRepository(state_store),
        agent_mailbox_repository=SqliteAgentMailboxRepository(state_store),
        agent_checkpoint_repository=SqliteAgentCheckpointRepository(state_store),
        agent_lease_repository=SqliteAgentLeaseRepository(state_store),
        agent_thread_binding_repository=SqliteAgentThreadBindingRepository(
            state_store,
        ),
        industry_instance_repository=SqliteIndustryInstanceRepository(state_store),
        media_analysis_repository=SqliteMediaAnalysisRepository(state_store),
        operating_lane_repository=SqliteOperatingLaneRepository(state_store),
        backlog_item_repository=SqliteBacklogItemRepository(state_store),
        operating_cycle_repository=SqliteOperatingCycleRepository(state_store),
        assignment_repository=SqliteAssignmentRepository(state_store),
        agent_report_repository=SqliteAgentReportRepository(state_store),
        goal_override_repository=SqliteGoalOverrideRepository(state_store),
        strategy_memory_repository=SqliteStrategyMemoryRepository(state_store),
        knowledge_chunk_repository=SqliteKnowledgeChunkRepository(state_store),
        memory_fact_index_repository=SqliteMemoryFactIndexRepository(state_store),
        memory_entity_view_repository=SqliteMemoryEntityViewRepository(state_store),
        memory_opinion_view_repository=SqliteMemoryOpinionViewRepository(state_store),
        memory_reflection_run_repository=SqliteMemoryReflectionRunRepository(state_store),
        workflow_template_repository=SqliteWorkflowTemplateRepository(state_store),
        workflow_preset_repository=SqliteWorkflowPresetRepository(state_store),
        workflow_run_repository=SqliteWorkflowRunRepository(state_store),
        fixed_sop_template_repository=SqliteFixedSopTemplateRepository(state_store),
        fixed_sop_binding_repository=SqliteFixedSopBindingRepository(state_store),
        routine_repository=SqliteExecutionRoutineRepository(state_store),
        routine_run_repository=SqliteRoutineRunRepository(state_store),
        prediction_case_repository=SqlitePredictionCaseRepository(state_store),
        prediction_scenario_repository=SqlitePredictionScenarioRepository(state_store),
        prediction_signal_repository=SqlitePredictionSignalRepository(state_store),
        prediction_recommendation_repository=SqlitePredictionRecommendationRepository(
            state_store,
        ),
        prediction_review_repository=SqlitePredictionReviewRepository(state_store),
        session_mount_repository=SessionMountRepository(state_store),
    )
