# -*- coding: utf-8 -*-
"""Unified state foundation for Phase 1.

This package introduces the minimal state-layer records, store, and
repositories that will become the single runtime truth source during the
carrier upgrade.
"""
from __future__ import annotations

from .models import (
    AgentCheckpointRecord,
    AgentLeaseRecord,
    AgentMailboxRecord,
    AgentProfileOverrideRecord,
    AgentRuntimeRecord,
    AgentReportRecord,
    AssignmentRecord,
    AgentThreadBindingRecord,
    BacklogItemRecord,
    CapabilityOverrideRecord,
    DecisionRequestRecord,
    ExecutionRoutineRecord,
    FixedSopBindingRecord,
    FixedSopTemplateRecord,
    GovernanceControlRecord,
    GoalRecord,
    GoalOverrideRecord,
    IndustryInstanceRecord,
    MediaAnalysisRecord,
    MetricRecord,
    OperatingCycleRecord,
    OperatingLaneRecord,
    PredictionCaseRecord,
    PredictionRecommendationRecord,
    PredictionReviewRecord,
    PredictionScenarioRecord,
    PredictionSignalRecord,
    ReportRecord,
    RuntimeFrameRecord,
    RoutineRunRecord,
    ScheduleRecord,
    StrategyMemoryRecord,
    TaskRecord,
    TaskRuntimeRecord,
    WorkflowPresetRecord,
    WorkflowRunRecord,
    WorkflowTemplateRecord,
)
from .models_knowledge import KnowledgeChunkRecord
from .models_memory import (
    MemoryEntityViewRecord,
    MemoryFactIndexRecord,
    MemoryOpinionViewRecord,
    MemoryReflectionRunRecord,
)
from .models_work_context import WorkContextRecord
from .work_context_service import WorkContextService
from .main_brain_service import (
    AgentReportService,
    AssignmentService,
    BacklogService,
    OperatingCycleService,
    OperatingLaneService,
)
from .store import SQLiteStateStore, STATE_SCHEMA_VERSION

__all__ = [
    "AgentReportService",
    "AgentCheckpointRecord",
    "AgentLeaseRecord",
    "AgentMailboxRecord",
    "AgentProfileOverrideRecord",
    "AssignmentService",
    "AgentRuntimeRecord",
    "AgentReportRecord",
    "AssignmentRecord",
    "AgentThreadBindingRecord",
    "BacklogService",
    "BacklogItemRecord",
    "CapabilityOverrideRecord",
    "DecisionRequestRecord",
    "ExecutionRoutineRecord",
    "FixedSopBindingRecord",
    "FixedSopTemplateRecord",
    "GovernanceControlRecord",
    "GoalRecord",
    "GoalOverrideRecord",
    "IndustryInstanceRecord",
    "MediaAnalysisRecord",
    "KnowledgeChunkRecord",
    "MemoryEntityViewRecord",
    "MemoryFactIndexRecord",
    "MemoryOpinionViewRecord",
    "MemoryReflectionRunRecord",
    "MetricRecord",
    "OperatingCycleService",
    "OperatingCycleRecord",
    "OperatingLaneService",
    "OperatingLaneRecord",
    "PredictionCaseRecord",
    "PredictionRecommendationRecord",
    "PredictionReviewRecord",
    "PredictionScenarioRecord",
    "PredictionSignalRecord",
    "ReportRecord",
    "RuntimeFrameRecord",
    "RoutineRunRecord",
    "ScheduleRecord",
    "SQLiteStateStore",
    "STATE_SCHEMA_VERSION",
    "StrategyMemoryRecord",
    "TaskRecord",
    "TaskRuntimeRecord",
    "WorkContextRecord",
    "WorkContextService",
    "WorkflowPresetRecord",
    "WorkflowRunRecord",
    "WorkflowTemplateRecord",
]
