# -*- coding: utf-8 -*-
"""Unified state foundation for Phase 1.

This package introduces the minimal state-layer records, store, and
repositories that will become the single runtime truth source during the
carrier upgrade.
"""
from __future__ import annotations

from .models import (
    AgentCheckpointRecord,
    AgentProfileOverrideRecord,
    AgentReportRecord,
    AutomationLoopRuntimeRecord,
    BuddyDomainCapabilityRecord,
    BuddyGrowthProjection,
    BuddyPresentation,
    AssignmentRecord,
    BacklogItemRecord,
    CapabilityCandidateRecord,
    CapabilityDonorRecord,
    CapabilityDonorTrustRecord,
    CapabilityPackageRecord,
    CapabilitySourceProfileRecord,
    CompanionRelationship,
    CapabilityOverrideRecord,
    DecisionRequestRecord,
    ExecutionRoutineRecord,
    ExecutionPolicyRecord,
    ExecutorEventRecord,
    ExecutorProtocolKind,
    ExecutorProviderRecord,
    ExecutorRuntimeInstanceRecord,
    ExecutorRuntimeScopeKind,
    ExecutorRuntimeStatus,
    ExecutorSelectionMode,
    ExecutorSidecarCompatibilityPolicyRecord,
    ExecutorSidecarInstallRecord,
    ExecutorSidecarInstallStatus,
    ExecutorSidecarReleaseRecord,
    ExecutorSidecarReleaseStatus,
    ExecutorThreadBindingRecord,
    ExecutorTurnRecord,
    ExternalCapabilityRuntimeInstanceRecord,
    FixedSopBindingRecord,
    FixedSopTemplateRecord,
    GovernanceControlRecord,
    GoalRecord,
    GoalOverrideRecord,
    GrowthTarget,
    HumanAssistTaskRecord,
    HumanProfile,
    IndustryInstanceRecord,
    LaneBudgetRecord,
    MediaAnalysisRecord,
    MetricRecord,
    ModelInvocationOwnershipMode,
    ModelInvocationPolicyRecord,
    OperatingCycleRecord,
    OperatingLaneRecord,
    PredictionCaseRecord,
    PredictionRecommendationRecord,
    PredictionReviewRecord,
    PredictionScenarioRecord,
    PredictionSignalRecord,
    ProjectProfileRecord,
    ReportRecord,
    RoleContractRecord,
    RoleExecutorBindingRecord,
    RuntimeFrameRecord,
    RoutineRunRecord,
    ScheduleRecord,
    SkillLifecycleDecisionRecord,
    SkillTrialRecord,
    StrategicUncertaintyRecord,
    StrategyMemoryRecord,
    StrategyTriggerRuleRecord,
    TaskRecord,
    TaskRuntimeRecord,
    WorkflowPresetRecord,
    WorkflowRunRecord,
    WorkflowTemplateRecord,
)
from .models_knowledge import KnowledgeChunkRecord
from .models_memory import (
    IndustryMemoryProfileRecord,
    IndustryMemorySlotPreferenceRecord,
    MemoryAliasMapRecord,
    MemoryConflictProposalRecord,
    MemoryContinuityDetailRecord,
    MemoryEntityViewRecord,
    MemoryFactIndexRecord,
    MemoryMergeResultRecord,
    MemoryOpinionViewRecord,
    MemoryRelationViewRecord,
    MemoryReflectionRunRecord,
    MemoryScopeDigestRecord,
    MemorySleepJobRecord,
    MemorySleepScopeStateRecord,
    MemoryStructureProposalRecord,
    MemorySoftRuleRecord,
    WorkContextMemoryOverlayRecord,
)
from .models_research import (
    ResearchSessionRecord,
    ResearchSessionRoundRecord,
)
from .models_surface_learning import (
    SurfaceCapabilityTwinRecord,
    SurfacePlaybookRecord,
)
from .models_work_context import WorkContextRecord
from .work_context_service import WorkContextService
from .human_assist_task_service import (
    HumanAssistTaskService,
    HumanAssistVerificationResult,
)
from .main_brain_service import (
    AgentReportService,
    AssignmentService,
    BacklogService,
    OperatingCycleService,
    OperatingLaneService,
)
from .capability_donor_service import CapabilityDonorService
from .capability_portfolio_service import CapabilityPortfolioService
from .donor_package_service import DonorPackageService
from .donor_source_service import DonorSourceService
from .donor_trust_service import DonorTrustService
from .skill_lifecycle_decision_service import SkillLifecycleDecisionService
from .skill_trial_service import SkillTrialService
from .external_runtime_service import ExternalCapabilityRuntimeService
from .executor_runtime_service import ExecutorRuntimeService
from .store import SQLiteStateStore, STATE_SCHEMA_VERSION

__all__ = [
    "AgentReportService",
    "AgentCheckpointRecord",
    "AgentProfileOverrideRecord",
    "AssignmentService",
    "AgentReportRecord",
    "AutomationLoopRuntimeRecord",
    "BuddyDomainCapabilityRecord",
    "BuddyGrowthProjection",
    "BuddyPresentation",
    "AssignmentRecord",
    "BacklogService",
    "BacklogItemRecord",
    "CapabilityCandidateRecord",
    "CapabilityDonorRecord",
    "CapabilityDonorService",
    "CapabilityDonorTrustRecord",
    "CapabilityOverrideRecord",
    "CapabilityPackageRecord",
    "CapabilityPortfolioService",
    "CapabilitySourceProfileRecord",
    "CompanionRelationship",
    "DecisionRequestRecord",
    "DonorPackageService",
    "DonorSourceService",
    "DonorTrustService",
    "ExecutionRoutineRecord",
    "ExecutionPolicyRecord",
    "ExecutorEventRecord",
    "ExecutorProtocolKind",
    "ExecutorProviderRecord",
    "ExecutorRuntimeInstanceRecord",
    "ExecutorRuntimeScopeKind",
    "ExecutorRuntimeStatus",
    "ExecutorRuntimeService",
    "ExecutorSelectionMode",
    "ExecutorSidecarCompatibilityPolicyRecord",
    "ExecutorSidecarInstallRecord",
    "ExecutorSidecarInstallStatus",
    "ExecutorSidecarReleaseRecord",
    "ExecutorSidecarReleaseStatus",
    "ExecutorThreadBindingRecord",
    "ExecutorTurnRecord",
    "ExternalCapabilityRuntimeInstanceRecord",
    "ExternalCapabilityRuntimeService",
    "FixedSopBindingRecord",
    "FixedSopTemplateRecord",
    "GovernanceControlRecord",
    "GoalRecord",
    "GoalOverrideRecord",
    "GrowthTarget",
    "HumanAssistTaskRecord",
    "HumanAssistTaskService",
    "HumanAssistVerificationResult",
    "HumanProfile",
    "IndustryInstanceRecord",
    "IndustryMemoryProfileRecord",
    "IndustryMemorySlotPreferenceRecord",
    "MediaAnalysisRecord",
    "KnowledgeChunkRecord",
    "LaneBudgetRecord",
    "MemoryAliasMapRecord",
    "MemoryConflictProposalRecord",
    "MemoryContinuityDetailRecord",
    "MemoryEntityViewRecord",
    "MemoryFactIndexRecord",
    "MemoryMergeResultRecord",
    "ModelInvocationOwnershipMode",
    "ModelInvocationPolicyRecord",
    "MemoryOpinionViewRecord",
    "MemoryRelationViewRecord",
    "MemoryReflectionRunRecord",
    "MemoryScopeDigestRecord",
    "MemorySleepJobRecord",
    "MemorySleepScopeStateRecord",
    "MemoryStructureProposalRecord",
    "MemorySoftRuleRecord",
    "MetricRecord",
    "OperatingCycleService",
    "OperatingCycleRecord",
    "OperatingLaneService",
    "OperatingLaneRecord",
    "PredictionCaseRecord",
    "PredictionRecommendationRecord",
    "PredictionReviewRecord",
    "PredictionScenarioRecord",
    "PredictionSignalRecord",
    "ProjectProfileRecord",
    "ResearchSessionRecord",
    "ResearchSessionRoundRecord",
    "ReportRecord",
    "RoleContractRecord",
    "RoleExecutorBindingRecord",
    "RuntimeFrameRecord",
    "RoutineRunRecord",
    "ScheduleRecord",
    "SQLiteStateStore",
    "STATE_SCHEMA_VERSION",
    "SkillLifecycleDecisionService",
    "SkillLifecycleDecisionRecord",
    "SkillTrialService",
    "SkillTrialRecord",
    "StrategicUncertaintyRecord",
    "StrategyMemoryRecord",
    "StrategyTriggerRuleRecord",
    "SurfaceCapabilityTwinRecord",
    "SurfacePlaybookRecord",
    "TaskRecord",
    "TaskRuntimeRecord",
    "WorkContextRecord",
    "WorkContextService",
    "WorkflowPresetRecord",
    "WorkflowRunRecord",
    "WorkflowTemplateRecord",
    "WorkContextMemoryOverlayRecord",
]
