# -*- coding: utf-8 -*-
from __future__ import annotations

from ..models import CapabilityMount


def list_system_capabilities() -> list[CapabilityMount]:
    mounts = [
        CapabilityMount(
            id="system:run_operating_cycle",
            name="run_operating_cycle",
            summary="Run the main-brain operating cycle before goal dispatch.",
            kind="system-op",
            source_kind="system",
            risk_level="auto",
            risk_description="Reconciles lanes/backlog/cycle/assignments/reports into the next execution slice.",
            environment_requirements=["kernel", "industry-state"],
            environment_description="Requires access to industry main-brain state and goal repositories.",
            evidence_contract=["industry-cycle-reconcile"],
            evidence_description="Records operating-cycle reconciliation and materialization decisions.",
            role_access_policy=["operator"],
            executor_ref="IndustryService.run_operating_cycle",
            replay_support=False,
            enabled=True,
            tags=["system", "industry", "cycle", "autonomy"],
        ),
        CapabilityMount(
            id="system:run_host_recovery",
            name="run_host_recovery",
            summary="Run the formal host recovery automation loop through the environment facade.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Processes actionable host events and advances governed recovery or re-observation decisions.",
            environment_requirements=["environment", "runtime-events"],
            environment_description="Requires access to the mounted environment facade and runtime host-event stream.",
            evidence_contract=["host-recovery", "runtime-event"],
            evidence_description="Records recovery-cycle decisions, affected sessions, and host-event follow-up outcomes.",
            role_access_policy=["operator"],
            executor_ref="EnvironmentService.run_host_recovery_cycle",
            replay_support=False,
            enabled=True,
            tags=["system", "environment", "host-recovery", "automation"],
        ),
        CapabilityMount(
            id="system:replay_routine",
            name="replay_routine",
            summary="Replay a formal execution routine through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Runs a persisted routine definition and records structured routine-run evidence.",
            environment_requirements=["kernel", "environment", "evidence"],
            environment_description="Requires access to the routine store, environment/session service, and evidence ledger.",
            evidence_contract=["routine-run", "kernel-task"],
            evidence_description="Records the parent kernel task plus the underlying routine run and evidence references.",
            role_access_policy=["all"],
            executor_ref="RoutineService.replay_routine",
            replay_support=False,
            enabled=True,
            tags=["system", "routine", "replay", "muscle-memory"],
        ),
        CapabilityMount(
            id="system:run_fixed_sop",
            name="run_fixed_sop",
            summary="Run a governed native fixed SOP binding through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Runs a native fixed SOP binding and records workflow/evidence backflow on the canonical chain.",
            environment_requirements=["kernel", "workflow", "evidence"],
            environment_description="Requires access to fixed SOP bindings, workflow runs, and the evidence ledger.",
            evidence_contract=["fixed-sop", "workflow-run", "kernel-task"],
            evidence_description="Records the parent kernel task plus the underlying fixed SOP run evidence and workflow linkage.",
            role_access_policy=["all"],
            executor_ref="FixedSopService.run_binding",
            replay_support=False,
            enabled=True,
            tags=["system", "workflow", "fixed-sop", "binding"],
        ),
        CapabilityMount(
            id="system:apply_role",
            name="apply_role",
            summary="Apply an agent role/profile override through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes the active agent role prompt and capability envelope.",
            environment_requirements=["kernel", "profile"],
            environment_description="Requires access to the persisted agent profile overrides.",
            evidence_contract=["agent-profile-update"],
            evidence_description="Records role/profile override updates for the target agent.",
            role_access_policy=["operator"],
            executor_ref="AgentProfileOverrideRepository.upsert_override",
            replay_support=False,
            enabled=True,
            tags=["system", "agent", "role", "profile"],
        ),
        CapabilityMount(
            id="system:update_industry_team",
            name="update_industry_team",
            summary="Apply a governed industry team topology or seat lifecycle update through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes the canonical industry team structure, temporary/career seat lifecycle, role roster, and derived execution plan.",
            environment_requirements=["kernel", "industry-state"],
            environment_description="Requires access to the persisted industry instance, goals, schedules, and team blueprint state.",
            evidence_contract=["industry-team-update", "agent-profile-update", "goal-dispatch"],
            evidence_description="Records the reconciled team topology, seat lifecycle mutations, and the resulting plan activation output.",
            role_access_policy=["operator"],
            executor_ref="IndustryService.update_instance_team",
            replay_support=False,
            enabled=True,
            tags=["system", "industry", "team", "governance"],
        ),
        CapabilityMount(
            id="system:send_channel_text",
            name="send_channel_text",
            summary="Send a text message to a channel session.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Sends outbound text to an external channel.",
            environment_requirements=["channel-session"],
            environment_description="Requires a live channel session to deliver text.",
            evidence_contract=["channel-send"],
            evidence_description="Records channel text dispatch operations.",
            role_access_policy=["operator"],
            executor_ref="ChannelManager.send_text",
            replay_support=False,
            enabled=True,
            tags=["system", "channel", "dispatch"],
        ),
        CapabilityMount(
            id="system:dispatch_query",
            name="dispatch_query",
            summary="Dispatch a query through the kernel-owned query execution service.",
            kind="system-op",
            source_kind="system",
            risk_level="auto",
            risk_description="Dispatches a query into the kernel-owned turn pipeline.",
            environment_requirements=["session"],
            environment_description="Requires a live session environment.",
            evidence_contract=["kernel-task", "query-dispatch"],
            evidence_description="Records query dispatch and execution results.",
            role_access_policy=["operator"],
            executor_ref="KernelTurnExecutor.stream_request",
            replay_support=False,
            enabled=True,
            tags=["system", "kernel", "dispatch", "turn"],
        ),
        CapabilityMount(
            id="system:dispatch_command",
            name="dispatch_command",
            summary="Dispatch a command through the kernel-owned turn execution service.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Commands mutate local runtime behavior and may require approval.",
            environment_requirements=["session"],
            environment_description="Requires a live session environment.",
            evidence_contract=["kernel-task", "command-dispatch"],
            evidence_description="Records command dispatch and execution results.",
            role_access_policy=["operator"],
            executor_ref="KernelTurnExecutor.stream_request",
            replay_support=False,
            enabled=True,
            tags=["system", "kernel", "dispatch", "command"],
        ),
        CapabilityMount(
            id="system:discover_capabilities",
            name="discover_capabilities",
            summary="Discover governed install-template and allowlisted remote capability candidates.",
            kind="system-op",
            source_kind="system",
            risk_level="auto",
            risk_description="Read-only discovery over mounted capabilities, runtime templates, and allowlisted remote catalogs.",
            environment_requirements=["capability-graph"],
            environment_description="Requires access to capability mounts, install templates, and allowlisted remote capability catalogs.",
            evidence_contract=["capability-discovery"],
            evidence_description="Records discovery queries, matched signals, and recommended governance paths.",
            role_access_policy=["all"],
            executor_ref="CapabilityDiscoveryService.discover",
            replay_support=False,
            enabled=True,
            tags=["system", "capability", "discovery", "recommendation"],
        ),
        CapabilityMount(
            id="system:set_capability_enabled",
            name="set_capability_enabled",
            summary="Enable or disable a capability through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes capability availability and must be governed.",
            environment_requirements=["configuration"],
            environment_description="Requires access to capability configuration stores.",
            evidence_contract=["capability-toggle"],
            evidence_description="Records capability enable/disable changes.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService.set_capability_enabled",
            replay_support=False,
            enabled=True,
            tags=["system", "capability", "governance"],
        ),
        CapabilityMount(
            id="system:delete_capability",
            name="delete_capability",
            summary="Delete a capability definition through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Deleting a capability is destructive and requires confirmation.",
            environment_requirements=["configuration"],
            environment_description="Requires access to capability configuration stores.",
            evidence_contract=["capability-delete"],
            evidence_description="Records capability deletion changes.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService.delete_capability",
            replay_support=False,
            enabled=True,
            tags=["system", "capability", "governance"],
        ),
        CapabilityMount(
            id="system:create_skill",
            name="create_skill",
            summary="Create a customized skill through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Writes a new skill bundle into local customized skill storage.",
            environment_requirements=["configuration", "workspace"],
            environment_description="Requires access to local customized skill storage.",
            evidence_contract=["config-write", "skill-create"],
            evidence_description="Records customized skill creation operations.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:create_skill",
            replay_support=False,
            enabled=True,
            tags=["system", "skill", "config", "governance"],
        ),
        CapabilityMount(
            id="system:install_hub_skill",
            name="install_hub_skill",
            summary="Install a hub skill bundle through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Imports a remote skill bundle into local customized skill storage.",
            environment_requirements=["network", "configuration", "workspace"],
            environment_description="Requires network access to the skill source and local skill storage.",
            evidence_contract=["config-write", "skill-install"],
            evidence_description="Records remote skill import operations and their source bundle.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:install_hub_skill",
            replay_support=False,
            enabled=True,
            tags=["system", "skill", "hub", "config", "governance"],
        ),
        CapabilityMount(
            id="system:trial_remote_skill_assignment",
            name="trial_remote_skill_assignment",
            summary="Preflight, install, and assign one allowlisted remote skill to a single target agent.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Imports a remote skill bundle and changes one agent capability allowlist for a governed trial.",
            environment_requirements=["network", "configuration", "workspace", "profile"],
            environment_description="Requires allowlisted network access, local skill storage, and persisted agent profile overrides.",
            evidence_contract=["skill-install", "agent-profile-update"],
            evidence_description="Records remote skill trial install and the resulting single-agent capability assignment.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:trial_remote_skill_assignment",
            replay_support=False,
            enabled=True,
            tags=["system", "skill", "trial", "governance", "agent"],
        ),
        CapabilityMount(
            id="system:update_channels_config",
            name="update_channels_config",
            summary="Update the full channel configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes channel ingress behavior and routing configuration.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "channel-config-update"],
            evidence_description="Records full channel configuration updates.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_channels_config",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "channel", "governance"],
        ),
        CapabilityMount(
            id="system:update_channel_config",
            name="update_channel_config",
            summary="Update a single channel configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes one channel's ingress behavior and policy.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "channel-config-update"],
            evidence_description="Records single-channel configuration updates.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_channel_config",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "channel", "governance"],
        ),
        CapabilityMount(
            id="system:update_heartbeat_config",
            name="update_heartbeat_config",
            summary="Update heartbeat scheduling configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes automated heartbeat behavior.",
            environment_requirements=["configuration", "schedule"],
            environment_description="Requires access to runtime configuration and scheduler state.",
            evidence_contract=["config-write", "heartbeat-config-update"],
            evidence_description="Records heartbeat configuration updates.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_heartbeat_config",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "heartbeat", "governance"],
        ),
        CapabilityMount(
            id="system:create_schedule",
            name="create_schedule",
            summary="Create a persisted runtime schedule through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Creates new autonomous runtime ingress and therefore requires confirmation.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and kernel-backed cron runtime.",
            evidence_contract=["schedule-write", "schedule-create"],
            evidence_description="Records schedule creation governance and the resulting persisted schedule.",
            role_access_policy=["operator"],
            executor_ref="CronManager.create_or_replace_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "governance", "runtime"],
        ),
        CapabilityMount(
            id="system:update_schedule",
            name="update_schedule",
            summary="Update a persisted runtime schedule through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Changes future autonomous execution timing or payload and requires confirmation.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and kernel-backed cron runtime.",
            evidence_contract=["schedule-write", "schedule-update"],
            evidence_description="Records schedule update governance and the resulting persisted schedule.",
            role_access_policy=["operator"],
            executor_ref="CronManager.create_or_replace_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "governance", "runtime"],
        ),
        CapabilityMount(
            id="system:delete_schedule",
            name="delete_schedule",
            summary="Delete a persisted runtime schedule through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Removes autonomous runtime ingress and therefore requires confirmation.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and kernel-backed cron runtime.",
            evidence_contract=["schedule-write", "schedule-delete"],
            evidence_description="Records schedule deletion governance and removal from the persisted scheduler.",
            role_access_policy=["operator"],
            executor_ref="CronManager.delete_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "governance", "runtime"],
        ),
        CapabilityMount(
            id="system:pause_schedule",
            name="pause_schedule",
            summary="Pause a runtime schedule through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Pauses future autonomous execution without deleting the schedule.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and runtime schedule state.",
            evidence_contract=["schedule-control", "schedule-pause"],
            evidence_description="Records schedule pause operations.",
            role_access_policy=["operator"],
            executor_ref="CronManager.pause_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "control", "runtime"],
        ),
        CapabilityMount(
            id="system:resume_schedule",
            name="resume_schedule",
            summary="Resume a paused runtime schedule through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Resumes future autonomous execution for a persisted schedule.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and runtime schedule state.",
            evidence_contract=["schedule-control", "schedule-resume"],
            evidence_description="Records schedule resume operations.",
            role_access_policy=["operator"],
            executor_ref="CronManager.resume_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "control", "runtime"],
        ),
        CapabilityMount(
            id="system:run_schedule",
            name="run_schedule",
            summary="Trigger a runtime schedule immediately through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Runs a persisted schedule immediately without changing its definition.",
            environment_requirements=["schedule", "kernel"],
            environment_description="Requires access to the persisted scheduler and runtime execution state.",
            evidence_contract=["schedule-control", "schedule-run"],
            evidence_description="Records immediate schedule execution requests.",
            role_access_policy=["operator"],
            executor_ref="CronManager.run_job",
            replay_support=False,
            enabled=True,
            tags=["system", "schedule", "control", "runtime"],
        ),
        CapabilityMount(
            id="system:update_agents_llm_routing",
            name="update_agents_llm_routing",
            summary="Update agent LLM routing configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes how runtime traffic is routed across model slots.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "llm-routing-update"],
            evidence_description="Records LLM routing configuration changes.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_agents_llm_routing",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "llm-routing", "governance"],
        ),
        CapabilityMount(
            id="system:update_agents_running_config",
            name="update_agents_running_config",
            summary="Update agent runtime behavior configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes runtime execution and memory compaction behavior.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "agent-running-config-update"],
            evidence_description="Records agent running configuration changes.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_agents_running_config",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "agent", "governance"],
        ),
        CapabilityMount(
            id="system:create_mcp_client",
            name="create_mcp_client",
            summary="Create a new MCP client configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Adds a new remote capability mount to runtime configuration.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "mcp-config-create"],
            evidence_description="Records MCP client creation operations.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:create_mcp_client",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "mcp", "governance"],
        ),
        CapabilityMount(
            id="system:update_mcp_client",
            name="update_mcp_client",
            summary="Update an MCP client configuration through the unified kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Changes remote capability transport, credentials, or enablement metadata.",
            environment_requirements=["configuration"],
            environment_description="Requires access to runtime configuration storage.",
            evidence_contract=["config-write", "mcp-config-update"],
            evidence_description="Records MCP client update operations.",
            role_access_policy=["operator"],
            executor_ref="CapabilityService._execute_system:update_mcp_client",
            replay_support=False,
            enabled=True,
            tags=["system", "config", "mcp", "governance"],
        ),
        CapabilityMount(
            id="system:delegate_task",
            name="delegate_task",
            summary="Delegate a child task to another agent through the kernel.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Creates a child task that may execute in another agent context.",
            environment_requirements=["kernel", "task"],
            environment_description="Requires access to kernel dispatcher and task store.",
            evidence_contract=["delegation", "kernel-task"],
            evidence_description="Records child task creation and delegation governance.",
            role_access_policy=["operator"],
            executor_ref="TaskDelegationService.delegate_task",
            replay_support=False,
            enabled=True,
            tags=["system", "delegation", "kernel", "task"],
        ),
        CapabilityMount(
            id="system:enqueue_task",
            name="enqueue_task",
            summary="Enqueue formal actor work into the resident mailbox.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Creates resident actor work that can execute later without a chat turn.",
            environment_requirements=["kernel", "actor-mailbox"],
            environment_description="Requires resident actor mailbox and runtime supervisor.",
            evidence_contract=["actor-mailbox", "kernel-task"],
            evidence_description="Records mailbox enqueue and resident runtime pickup.",
            role_access_policy=["operator"],
            executor_ref="ActorMailboxService.enqueue_item",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "mailbox", "runtime"],
        ),
        CapabilityMount(
            id="system:pause_actor",
            name="pause_actor",
            summary="Pause a resident actor so queued work stops executing.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Suspends actor execution without deleting state.",
            environment_requirements=["kernel", "actor-runtime"],
            environment_description="Requires access to the persisted actor runtime store.",
            evidence_contract=["actor-runtime"],
            evidence_description="Records actor desired-state changes.",
            role_access_policy=["operator"],
            executor_ref="ActorMailboxService.pause_actor",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "pause"],
        ),
        CapabilityMount(
            id="system:resume_actor",
            name="resume_actor",
            summary="Resume a paused resident actor.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Resumes queued resident actor execution.",
            environment_requirements=["kernel", "actor-runtime"],
            environment_description="Requires access to the persisted actor runtime store.",
            evidence_contract=["actor-runtime"],
            evidence_description="Records actor resume transitions.",
            role_access_policy=["operator"],
            executor_ref="ActorMailboxService.resume_actor",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "resume"],
        ),
        CapabilityMount(
            id="system:cancel_actor_task",
            name="cancel_actor_task",
            summary="Cancel queued or active actor mailbox work.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Cancels resident actor work items or running tasks.",
            environment_requirements=["kernel", "actor-mailbox"],
            environment_description="Requires access to actor mailbox and dispatcher state.",
            evidence_contract=["actor-mailbox", "kernel-task"],
            evidence_description="Records mailbox cancellation and kernel task cancellation requests.",
            role_access_policy=["operator"],
            executor_ref="ActorMailboxService.cancel_actor_task",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "cancel"],
        ),
        CapabilityMount(
            id="system:retry_actor_mailbox",
            name="retry_actor_mailbox",
            summary="Retry a resident actor mailbox item and optionally resume execution immediately.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Requeues resident actor work that may execute again.",
            environment_requirements=["kernel", "actor-mailbox", "actor-runtime"],
            environment_description="Requires access to actor mailbox state and supervisor pickup.",
            evidence_contract=["actor-mailbox", "kernel-task"],
            evidence_description="Records mailbox retry and optional immediate runtime pickup.",
            role_access_policy=["operator"],
            executor_ref="ActorMailboxService.retry_item",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "mailbox", "retry"],
        ),
        CapabilityMount(
            id="system:list_teammates",
            name="list_teammates",
            summary="List currently available teammates for actor collaboration.",
            kind="system-op",
            source_kind="system",
            risk_level="auto",
            risk_description="Read-only actor roster lookup.",
            environment_requirements=["actor-runtime"],
            environment_description="Requires access to actor runtime and thread bindings.",
            evidence_contract=["call-record"],
            evidence_description="Records teammate roster lookups.",
            role_access_policy=["all"],
            executor_ref="ActorMailboxService.list_teammates",
            replay_support=False,
            enabled=True,
            tags=["system", "actor", "team"],
        ),
        CapabilityMount(
            id="system:run_learning_strategy",
            name="run_learning_strategy",
            summary="Run the main-brain learning strategy cycle for capability, skill, and routine upgrades.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Generates governed proposals/patches and may auto-apply low-risk upgrades.",
            environment_requirements=["learning", "evidence"],
            environment_description="Requires learning engine and evidence ledger.",
            evidence_contract=["learning-strategy", "patch"],
            evidence_description="Records strategy decisions and patch outcomes.",
            role_access_policy=["operator"],
            executor_ref="LearningService.run_strategy_cycle",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "strategy"],
        ),
        CapabilityMount(
            id="system:auto_apply_patches",
            name="auto_apply_patches",
            summary="Auto-apply low-risk patches.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Applies low-risk patches automatically.",
            environment_requirements=["learning"],
            environment_description="Requires learning engine storage.",
            evidence_contract=["patch-apply", "growth-event"],
            evidence_description="Records patch application and growth events.",
            role_access_policy=["operator"],
            executor_ref="LearningService.auto_apply_low_risk_patches",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "patch"],
        ),
        CapabilityMount(
            id="system:apply_patch",
            name="apply_patch",
            summary="Apply a patch (confirmation required).",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Applying patches can change system behavior.",
            environment_requirements=["learning"],
            environment_description="Requires learning engine storage.",
            evidence_contract=["patch-apply", "growth-event"],
            evidence_description="Records patch application and growth events.",
            role_access_policy=["operator"],
            executor_ref="LearningService.apply_patch",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "patch"],
        ),
        CapabilityMount(
            id="system:approve_patch",
            name="approve_patch",
            summary="Approve a pending patch.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Approving a patch authorizes later application.",
            environment_requirements=["learning"],
            environment_description="Requires learning engine storage.",
            evidence_contract=["patch-approval"],
            evidence_description="Records patch approval decisions.",
            role_access_policy=["operator"],
            executor_ref="LearningService.approve_patch",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "patch"],
        ),
        CapabilityMount(
            id="system:reject_patch",
            name="reject_patch",
            summary="Reject a pending patch.",
            kind="system-op",
            source_kind="system",
            risk_level="guarded",
            risk_description="Rejecting a patch stops further application.",
            environment_requirements=["learning"],
            environment_description="Requires learning engine storage.",
            evidence_contract=["patch-rejection"],
            evidence_description="Records patch rejection decisions.",
            role_access_policy=["operator"],
            executor_ref="LearningService.reject_patch",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "patch"],
        ),
        CapabilityMount(
            id="system:rollback_patch",
            name="rollback_patch",
            summary="Rollback an applied patch.",
            kind="system-op",
            source_kind="system",
            risk_level="confirm",
            risk_description="Rollback changes system behavior and requires confirmation.",
            environment_requirements=["learning"],
            environment_description="Requires learning engine storage.",
            evidence_contract=["patch-rollback"],
            evidence_description="Records patch rollback actions.",
            role_access_policy=["operator"],
            executor_ref="LearningService.rollback_patch",
            replay_support=False,
            enabled=True,
            tags=["system", "learning", "patch"],
        ),
    ]
    return mounts


__all__ = ["list_system_capabilities"]

